# Generated by Django 2.1.3 on 2018-11-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClimbingShoes',
            new_name='ClimbingShoe',
        ),
    ]
